### PR TITLE
Provide PHP 8.3.0beta1 support

### PR DESCRIPTION
**Pull request by GrahamCampbell**
~WIP: waiting on the download URL, as it will be namespaced to one of the release managers.~

~UPDATE: When ~alpha3~beta1 is released, this PR should be ready.~ 🚢

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Looks like the mbstring extension does not build.

**Comment by GrahamCampbell** [comment]
I'm going to comment it out for now, until they get this fixed, so we can move forward with this.

**Comment by mnapoli** [comment]
Ah I'm guessing there's no xdebug version that supports 8.3 as well?

**Comment by GrahamCampbell** [comment]
Let's see if mbstring builds on alpha2, tomorrow.

**Comment by GrahamCampbell** [comment]
Raised an issue with PHP.

**Comment by GrahamCampbell** [comment]
Ready for review, @mnapoli. 🎉

**Review by mykiwi — APPROVED** [review]

**Comment by mnapoli** [comment]
Oh the build is green, nice! I was on holidays, catching up today or tomorrow!

**Comment by GrahamCampbell** [comment]
I hope you had a good break! 🏖️🍹

**Comment by mnapoli** [comment]
Thanks for the great work!

**Pull request merged**
