### PR TITLE
Confirm that the PHP 8.0 build fails without the patch for OpenSSL 3.2

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by mnapoli** [comment]
I'd rather not patch PHP 8.0, I don't see a reason to do so?

**Comment by GrahamCampbell** [comment]
This PR was created just temporarily to confirm that the other PR was good. OpenSSL 1.1.1 has known security vulnerabilities, and multiple other OS distributions that ship PHP 8.0 with OpenSSL 3.0 apply this patch - this is where it came from.

**Comment by mnapoli** [comment]
Right, but PHP 8.0 is not maintained at all in a few days, so I don't think it will be a huge difference.

**Comment by GrahamCampbell** [comment]
I'd still like to make the change to have Bref 2 using the same OpenSSL version across the board.

**Pull request closed without merging**
