### PR TITLE
Add "Dockerfile" workflow running Hadolint

### PR DESCRIPTION
**Pull request by szepeviktor**
This workflow will spot problems before Dockerfiles are used.

> [!WARNING]
> Hadolint is going to hurt your feelings!

[_source_](https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows)

---

BTW I name workflows based on the object (noun), not the action (verb).
So the viktoroid version of `tests.yml` would be `images.yml` or `docker-images.yml` - meaning "Build images and Test images"

### CODE REVIEW

**Comment by szepeviktor** [comment]
If you are into OCI: add `.hadolint.yaml`

```yaml
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
label-schema:
    org.opencontainers.image.created: "rfc3339"
    org.opencontainers.image.authors: "text"
    org.opencontainers.image.url: "url"
    org.opencontainers.image.documentation: "url"
    org.opencontainers.image.source: "url"
    org.opencontainers.image.version: "semver"
    org.opencontainers.image.revision: "hash"
    org.opencontainers.image.vendor: "text"
    org.opencontainers.image.licenses: "spdx"
    org.opencontainers.image.ref.name: "text"
    org.opencontainers.image.title: "text"
    org.opencontainers.image.description: "text"
    # org.opencontainers.image.base.digest: "text"
    # org.opencontainers.image.base.name: "text"
```

**Comment by mnapoli** [comment]
I don't understand this PR, sorry.

**Comment by szepeviktor** [comment]
This PR adds a new workflow that run "Hadolint" on each commit.
Hadolint has dozen of rules to keep Dockerfile error-free on the long-term.

**Comment by szepeviktor** [comment]
It is better to close this one.
Hadolint is still available to you.

**Pull request closed without merging**
