### PR TITLE
Upgrade to PHP 8.1.15 and 8.2.2

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by mnapoli** [comment]
Ah, I'm looking into configuring the Depot token so that it can be used on PRs. I'll let you know!

**Comment by mnapoli** [comment]
@GrahamCampbell could you rebase? Let's see if the OIDC auth works better!

**Comment by GrahamCampbell** [comment]
> 1 workflow awaiting approval

;)

**Comment by mnapoli** [comment]
woops!

**Comment by mnapoli** [comment]
I opened https://github.com/depot/bake-action/issues/5 to move this forward

**Comment by mnapoli** [comment]
OK https://github.com/brefphp/aws-lambda-layers/pull/49 adds a bit of complexity and skips ARM on pull requests, but at least it unblocks the situation right now.

Builds will still run on ARM once merged to master, and x86 builds and ARM builds are identical now, so failures after merging should be very rare.

Could you rebase again? Thanks!

**Comment by mnapoli** [comment]
Thanks!

**Pull request merged**
