### PR TITLE
PHP 8.4.0beta5

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
apcu build is broken. Is there a reason we include apcu in the bref base layer? Does it not work as an extension?

**Comment by mnapoli** [comment]
This extension is built-in the main bref layers.

**Comment by GrahamCampbell** [comment]
I see you triggered a rebuild, but I don't think it'll succeed, as changes are needed to the apcu extension source to make it work properly on beta5 (and later).

**Comment by mnapoli** [comment]
Yep, I figured it doesn't hurt to retry 🤷 But the error message didn't look like it would make any difference.

**Comment by GrahamCampbell** [comment]
Building the extension from source seems to work. Not sure if what I've done is actually identical to what we had before. Was the extension previously being enabled using an ini file?

**Comment by GrahamCampbell** [comment]
APCu 5.1.24 has now been released.

**Comment by mnapoli** [comment]
Nice!

**Pull request merged**
